WIP
geotrellis/geotrellis-site-deployment pull request #2
Opened 2017-02-17 22:32 UTC by hectcastro

Still missing:

- [ ] HTTP listener and HTTP to HTTPS support
- [ ] Demos don't appear to be working (Nginx configuration suspect)
- [ ] Add additional variables file
- [ ] Set JVM heap size explicitly
- ...

2017-03-23 19:00 UTC, tnation14 requested changes
The terraform files are configured correctly, and I was able to run `scripts/infra plan` successfully. However, when I provisioning my VM, I noticed that `aws` and `terraform` are not installed during provisioning. The AWS environment isn't configured either. Can that be fixed here or should I create a separate issue?

2017-03-23 19:00 UTC, tnation14 commented on scripts/infra
> +                terraform get -update
This command can be removed, since `terraform init` takes care of updating modules.

2017-03-23 19:31 UTC, hectcastro commented
I did not even realize there was a `Vagrantfile` at the root of this project. I never made use of it while I was working.

I opened the following issues to address outstanding issues:

- https://github.com/geotrellis/geotrellis-site-deployment/issues/6
- https://github.com/geotrellis/geotrellis-site-deployment/issues/5
- https://github.com/geotrellis/geotrellis-site-deployment/issues/4
- https://github.com/geotrellis/geotrellis-site-deployment/issues/3

2017-03-27 16:17 UTC, tnation14 approved these changes

2017-03-27 16:20 UTC, merged