Update Vagrant project dependencies and folder structure
geotrellis/geotrellis-site-deployment pull request #7
Opened 2017-05-03 19:36 UTC by tnation14

# OVERVIEW
This PR updates `terraform` and `awscli` versions, and reorganizes Terraform and Ansible resources to conform to the organizational standards set in other repos. The `Vagrantfile` and `scripts/infra` have been updated to reflect this change.

- Bump Terraform version to 0.9.3
- Move `terraform` and `ansible` directories to a `deployment/` folder
- Add Ansible role to install `awscli==11.82.*` and configure the AWS environment.
- Mount `~/.aws` into the VM.

# TESTING
- Follow the `Environment Setup` steps in the `README` to provision the VM.
- `vagrant ssh`, then run `scripits/infra plan` according to the instructions in the `README`. Ensure that a) the command runs successfully and b) no changes are necessary.

Fixes #3

2017-05-03 20:10 UTC, hectcastro requested changes

2017-05-03 20:10 UTC, hectcastro commented on deployment/ansible/roles/gtsite.awscli/tasks/main.yml
> +  pip: name=awscli version={{ awscli_version }}
We have a role that can be used for installing the AWS CLI: https://github.com/azavea/ansible-aws-cli

2017-05-03 20:10 UTC, hectcastro commented on README.md
> +$ vagrant up --provision
I think that it would be good to replace this step with the usual `setup` script that does mostly this.

2017-05-04 15:23 UTC, tnation14 commented on deployment/ansible/roles/gtsite.awscli/tasks/main.yml
> +  pip: name=awscli version={{ awscli_version }}
Thanks. I knew we had this role but I couldn't find it; I was searching for `ansible-awscli`.

2017-05-04 20:43 UTC, tnation14 commented
Updated.

2017-05-05 13:50 UTC, hectcastro commented on Vagrantfile
> +                           "java_flavor"                          => "oracle",
Why is Java being installed inside the VM? The goal of this repository is only support AWS infrastructure management (the core column on the whiteboard from yesterday).

2017-05-05 15:06 UTC, tnation14 commented
Java references have been removed, and `scripts/setup` now only runs `vagrant up --provision`.

2017-05-05 15:43 UTC, hectcastro approved these changes

2017-05-05 20:12 UTC, merged